### ISSUE TITLE
Browsing History!?

### ISSUE THREAD

**Issue by malins** [AminoffZ/github-repo-size#126]
Why does this extension request access to my browsing history?

**Comment by mAmineChniti** [comment]
As far as i know the extension doesn't do that, is there any example you can provide of the extension accessing your browser history ?

**Comment by mAmineChniti** [comment]
Ah yes, the extension isn't actually reading your browser history and i can assure you we don't have anything of that sort in the code you can go through it yourself, but we're using the tabs API to access the url of the github tab :
`Security and Privacy Implications
Read Browsing History: Since the extension can access the URLs of the tabs, it effectively has the ability to read the user's browsing history. This is why the warning "Read your browsing history" is displayed when an extension requests the "tabs" permission.`
